workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      android:
        gradle: 7.4
      java: 17
    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - build/app/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
