workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      java: 17
      vars:
        GRADLE_WRAPPER: "./gradlew"
    scripts:
      - name: Build APK
        script: |
          chmod +x $GRADLE_WRAPPER
          $GRADLE_WRAPPER assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
