workflows:
  build_kotlin_app:
    name: Manual Kotlin Build
    max_build_duration: 30
    environment:
      android:
        image: android-31
    scripts:
      - name: Make Gradle Executable
        script: chmod +x ./gradlew

      - name: Build APK
        script: ./gradlew assembleRelease

      - name: Upload to Telegram
        script: |
          curl -F document=@app/build/outputs/apk/release/app-release.apk \
               "https://api.telegram.org/bot7559836941:AAFFgyR1TWjyYmmNc-IPyr6NpZZdUXRrP_c/sendDocument?chat_id=6814152338&caption=تم بناء التطبيق بنجاح"
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
