name: Build APK

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: تحميل الملفات من GitHub
        uses: actions/checkout@v3

      - name: إعداد Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: إعطاء صلاحيات للملف gradlew
        run: chmod +x gradlew

      - name: بناء ملف APK
        run: ./gradlew assembleDebug

      - name: حفظ ملف APK في النتائج
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
